# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft / Fabric
# Diese drei Werte muessen exakt zur Zielversion passen (siehe https://fabricmc.net/develop/).
minecraft_version=26.2
loader_version=0.19.5
fabric_version=0.159.0+26.2

# Mod
mod_version=1.0.0
maven_group=de.zurret
archives_base_name=vanishing-ground
